### ISSUE TITLE
Multi-project mode for GitHub Action

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/github-action#35]
- [x] add input to enable multi project mode if array of directories/config provided
- [x] run `collect` for each project and produce individual artifacts (`code-pushup-report-<project-name>`)
- [x] run `compare` for each project and merge diffs into single markdown body (using implementation from code-pushup/cli#731)

:arrow_down: More information in comments below.

**Comment by matejchalk** [comment]
I did some research and concluded that the GitHub Action will have to know about specific monorepo tool conventions, otherwise the configuration burden on the user would be huge, and action inputs don't have support for complex data structures.

I've distinguished the following monorepo scenarios to get started (JS -focused):
- Nx, Turborepo - cacheable, will use the `monorepo` input
- PNPM, Yarn, NPM - concept of packages/workspaces, will use the `workspace` input
- no tooling - just folders with individual configs, fallback for non-JS codebases, will use the `projects` input

### Nx 

```yml
- uses: code-pushup/github-action@v0
  with:
    monorepo: nx
```

- List projects using `npx nx show projects --with-target=code-pushup --json`.
- Get individual project config using `npx nx show project <name> --json`.
- Execute Code PushUp commands with `npx nx code-pushup <name> --` for cached executions.
  - **Important**: Target executor must forward both commands and arguments to the underlying `code-pushup` binary (breaks assumptions of current `@code-pushup/nx-plugin:autorun` executor).
- TBD: If `code-pushup` target isn't used (i.e. they're not using our Nx plugin), then we could still fall back on search for `code-pushup.config.{ts,mjs,js}` and running those using the binary (uncached).

### Turborepo

```yml
- uses: code-pushup/github-action@v0
  with:
    monorepo: turbo
```

- Determine workspace type using `packageManager` field in `package.json`.
- Check for `code-pushup` command in `turbo.json`.
  - If present, use `npx turbo run code-pushup -F <name> --` for cached executions.
  - Otherwise, behave as if `workspace: pnpm|npm|yarn|bun` was set.
- Use package manager to list projects. 

### PNPM workspace

```yml
- uses: code-pushup/github-action@v0
  with:
    workspace: pnpm
```

- List projects using `packages` glob in `pnpm-workspace.yaml`.
- Determine project name from `name` in each package's `package.json`.
- Run Code PushUp commands using `pnpm -F <name> code-pushup` (script > binary).

### Yarn workspace

```yml
- uses: code-pushup/github-action@v0
  with:
    workspace: yarn
```

- List projects using `workspaces` glob in root `package.json`.
- Determine project name from `name` in each package's `package.json`.
- Run Code PushUp commands using `yarn workspace <name> code-pushup` (script > binary).

### NPM workspace

```yml
- uses: code-pushup/github-action@v0
  with:
    workspace: npm
```

- List projects using `workspaces` glob in root `package.json`.
- Determine project name from `name` in each package's `package.json`.
- Run Code PushUp commands using `npm -w <name> run code-pushup --` (script) or `npm -w <name> exec code-pushup --` (binary).

### no tooling

```yml
- uses: code-pushup/github-action@v0
  with:
    projects: frontend,backend
```

- Folders explicitly listed, separated by commas, each may contain globs.
- Determine project name from `name` in `package.json` if available, otherwise fallback on folder/path.
- Run Code PushUp in each project directory using `npx --no-install code-pushup`.
