### ISSUE TITLE
GitLab template

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/github-action#58]
As a GitLab user, I would like to easily configure Code PushUp comparison comments in GitLab CI/CD, similarly to how GitHub users have a simple setup using [`code-pushup/github-action`](https://github.com/marketplace/actions/code-pushup).

Unfortunately, GitLab pipelines don't offer anything as comprehensive as shared actions in GitHub. The closest equivalent is to distribute a GitLab template.

GitLab docs:
- [Use CI/CD configuration from other files](https://docs.gitlab.com/ee/ci/yaml/includes.html)
- [Define inputs for configuration added with `include`](https://docs.gitlab.com/ee/ci/yaml/inputs.html)

The GitLab template would include a script to run equivalent logic as in the GitHub Action. Configuration should be possible via `inputs` or overriding template properties (e.g. setting custom `image` or adding a `before_script`).

To be able to easily test the template end-to-end, it would be best to develop this template in a GitLab repository, so that it can run Code PushUp on itself.

<details><summary>current GitLab CI/CD integrations (no comparisons, only upload)</summary>
<p>

In React repo:

```yaml
code-pushup:
  <<: *rule-main-and-release-on-success
  <<: *resolve-deps
  <<: *cache-pull
  stage: pre-deploy
  allow_failure: true
  tags: [high-performance]
  script:
    - yarn -s run code-pushup
  artifacts:
    expire_in: 1 days
    paths:
      - .code-pushup/
```

In PHP repo where Code PushUp is run only on tests in Cypress folder:

```yaml
# cypress/.gitlab-ci.yml

code-pushup:
  stage: report
  image: node:lts
  cache:
    <<: *global_cache
  allow_failure: true
  script:
    - !reference [.create_npmrc, script]
    - yarn install --frozen-lockfile
    - cd cypress
    - yarn code-pushup
  artifacts:
    expire_in: 1 days
    paths:
      - cypress/.code-pushup/
```

In Python repo (needs image with both Node.js and Python installed):

```yaml
code-pushup:
  stage: code_review
  extends: .base-job
  image: nikolaik/python-nodejs:python3.11-nodejs20
  allow_failure: true
  before_script:
  - export POETRY_HTTP_BASIC_SKYPICKER_USERNAME=${CI_REGISTRY_USER}
  - export POETRY_HTTP_BASIC_SKYPICKER_PASSWORD=${CI_JOB_TOKEN}
  - poetry install
  - poetry self add poetry-audit-plugin
  - python -m pip install pylint
  - cd code-pushup
  - yarn install --frozen-lockfile
  script:
  - yarn code-pushup
  artifacts:
    expire_in: 1 days
    paths:
    - code-pushup/.code-pushup/
```

</p>
</details> 

### Acceptance criteria

- [x] new Code PushUp GitLab organization is created
- [x] new repository for GitLab template is created
- [x] template can be included in any GitLab project via URL
- [x] script runs Code PushUp on source and target branches and uploads to portal and/or artifacts (artifact downloaded for caching)
- [x] if a MR is open, script compares reports and posts Markdown summary as MR comment using GitLab API
- [x] investigate GitHub annotations equivalent and plan follow-up issue
  - #110  
- [x] consider how to integrate GitHub Action's monorepo mode (https://github.com/code-pushup/github-action/issues/35), incl. how can we best handle shared code, and plan follow-up issue
